comun: A community table with samples as rows and taxa as columns. 

net<-function(comun){
  require(Hmisc)
  require(igraph)
  b_to<-rcorr(comun,type="spearman")
  r<-b_to$r
  p<-b_to$P
  r[r<0.7]<-0
  p<-p.adjust(p, method="fdr")
  q<-matrix(p,nrow=ncol(comun),ncol=ncol(comun))
  q[q<0.05]<-1
  q[q>0.05&q<1]<-0
  gg<-r*q
  diag(gg) <- 0
  g <- graph.adjacency(gg, weighted=TRUE, mode="undirected")
  g <- simplify(g)
  return(g)
}

###net: the network generated by function net()
###Caculation of node-level topological features
degree(net)####Degree
betweenness(net)####Betweenness centrality
closeness(net)####Closeness centrality

###Caculation of network-level topological features
length(V(net))###Number of nodes
length(E(net))###Number of edges
mean(degree(net))###Average degree
transitivity(net)###Clustering coefficient
average.path.length(net)###Average path length
diameter(net)###Network diameter
graph.density(net)###Graph density


##Caculation of z score and c score 

zi.pi<-function(nodes_bulk,z.bulk,type=1,
                modularity_class='modularity_class',degree='degree'){
  
  z.bulk[abs(z.bulk)>0]<-1
  module<-which(colnames(nodes_bulk)==modularity_class)
  module.max<-max(nodes_bulk[,module])
  degree<-which(colnames(nodes_bulk)==degree)
  bulk.module<-list(NA)
  length(bulk.module)<-module.max
  
  for(i in 1:max(nodes_bulk[,module])){
    bulk.module[[i]]<-z.bulk[which(nodes_bulk[,module]==i),which(nodes_bulk[,module]==i)]
    bulk.module[[i]]<-as.data.frame(bulk.module[[i]])
    rownames(bulk.module[[i]])<-rownames(z.bulk)[which(nodes_bulk[,module]==i)]
    colnames(bulk.module[[i]])<-colnames(z.bulk)[which(nodes_bulk[,module]==i)]
  }
  
  # within-module degree z
  z_bulk<-list(NA)
  length(z_bulk)<-module.max
  
  for(i in 1:length(z_bulk)){
    z_bulk[[i]]<-bulk.module[[i]][,1]
    z_bulk[[i]]<-as.data.frame(z_bulk[[i]])
    colnames(z_bulk[[i]])<-"z"
    rownames(z_bulk[[i]])<-rownames(bulk.module[[i]])
  }
  
  #Caculation of z score 
  for(i in 1:max(nodes_bulk[,module])){
    if(length(bulk.module[[i]])==1){
      z_bulk[[i]][,1]<-0
    }else if(sum(bulk.module[[i]])==0){
      z_bulk[[i]][,1]<-0
    }else{
      k<-rowSums(bulk.module[[i]])
      mean<-mean(k)
      sd<-sd(k)
      if (sd==0){
        z_bulk[[i]][,1]<-0
      }else{
        z_bulk[[i]][,1]<-(k-mean)/sd
      }
    }
  }
  
  
  for(i in 2:max(nodes_bulk[,module])) {
    z_bulk[[i]]<-rbind(z_bulk[[i-1]],z_bulk[[i]])
  }
  z_bulk<-z_bulk[[module.max]]
  
  bulk.module1<-list(NA)
  length(bulk.module1)<-module.max
  
  for(i in 1:max(nodes_bulk[,module])){
    bulk.module1[[i]]<-z.bulk[,which(nodes_bulk[,module]==i)]
    bulk.module1[[i]]<-as.data.frame(bulk.module1[[i]])
    rownames(bulk.module1[[i]])<-rownames(z.bulk)
    colnames(bulk.module1[[i]])<-colnames(z.bulk)[which(nodes_bulk[,module]==i)]
  }
  
  #among-module connectivity c
  c_bulk<-list(NA)
  length(c_bulk)<-module.max
  
  for(i in 1:length(c_bulk)){
    c_bulk[[i]]<-z.bulk[,1]
    c_bulk[[i]]<-as.matrix(c_bulk[[i]])
    colnames(c_bulk[[i]])<-"c"
    rownames(c_bulk[[i]])<-rownames(z.bulk)
    c_bulk[[i]][,1]<-NA
  }
  
  
  for(i in 1:max(nodes_bulk[,module])){
    c_bulk[[i]]<-rowSums(bulk.module1[[i]])
    c_bulk[[i]]<-as.matrix(c_bulk[[i]])
    c_bulk[[i]]<-c_bulk[[i]]*c_bulk[[i]]
    colnames(c_bulk[[i]])<-"c"
    rownames(c_bulk[[i]])<-rownames(z.bulk)
  }
  
  
  for(i in 2:max(nodes_bulk[,module])){
    c_bulk[[i]]<-c_bulk[[i]]+c_bulk[[i-1]]
  }
  c_bulk<-c_bulk[[module.max]]
  
  c_bulk1<-1-(c_bulk/(nodes_bulk[,degree]*nodes_bulk[,degree]))
  colnames(c_bulk1)<-"c"
  
  z_c_bulk<-c_bulk1
  z_c_bulk<-as.data.frame(z_c_bulk)
  z_c_bulk$z<-z_bulk[match(rownames(c_bulk1),rownames(z_bulk)),]
  z_c_bulk<-z_c_bulk[,c(2,1)]
  names(z_c_bulk)[1:2]<-c('z','c')
  
  ##type==2,only z and c score；type==1, merge the result of type==1 with the data of nodes_bulk
  if (type==1) {
    z_c_bulk$otu.names<-rownames(z_c_bulk)
    nodes_bulk$otu.names<-rownames(nodes_bulk)
    result<-merge(z_c_bulk,nodes_bulk,by='otu.names')  
  }
  if (type==2) {
    result<-z_c_bulk  
  }
  
  result
}

##nodes_bulk: A community table with samples as rows and network topological features including network module and degree as columns.
##z.bulk: An adjacency matrix
result.1<-zi.pi(nodes_bulk,z.bulk,type=1,modularity_class='modularity_class',degree='degree')
result.2<-zi.pi(nodes_bulk,z.bulk,type=2,modularity_class='modularity_class',degree='degree')

## 
zp_bulk$classi[which(zp_bulk$z<=2.5&zp_bulk$c<=0.62)]<-"Peripherals"
zp_bulk$classi[which(zp_bulk$z<=2.5&zp_bulk$c>0.62)]<-"Connectors"
zp_bulk$classi[which(zp_bulk$z>2.5&zp_bulk$c<=0.62)]<-"Module hubs"
zp_bulk$classi[which(zp_bulk$z>2.5&zp_bulk$c>0.62)]<-"Network hubs"


zp_bulk$classi<-factor(zp_bulk$classi,levels=c("Peripherals","Connectors",
                                               "Module hubs","Network hubs"))
library(ggplot2)
xmaj<-c(0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8)
ymaj<-c(-2,-1,0,1,2,3,4,5)

cols<-c("coral2","darkolivegreen4","dodgerblue2","hotpink2")
cols1<-c("coral2","dodgerblue2")


ggplot(zp_bulk,aes(c,z,colour=classi))+geom_point()+theme_bw()+
  facet_wrap(com~.,2)+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),
        legend.position ="none")+labs(x="Among-module connectivity (c)",
                                      y="Within-module connectivity (z)")+geom_hline(yintercept=2.5)+geom_vline(xintercept=0.62)+
  scale_colour_manual(values = cols)

scale_x_continuous(breaks=xmaj,labels=xmaj)+
  scale_y_continuous(breaks=ymaj,labels=ymaj)

ggplot(key,aes(x=com))+
  geom_histogram(stat="count")+facet_wrap(v_phylum~.)
